//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int Id { get; set; }
        public int ProduserId { get; set; }
        public int BodyTypesId { get; set; }
        public string Name { get; set; }
    
        public virtual BodyType BodyTypes { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
        public virtual Produser Produsers { get; set; }
    }
}
