//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGAI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAIEntities : DbContext
    {
        public GAIEntities()
            : base("name=GAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyTypeClassification> BodyTypeClassifications { get; set; }
        public virtual DbSet<BodyType> BodyTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FinesType> FinesTypes { get; set; }
        public virtual DbSet<Produser> Produsers { get; set; }
        public virtual DbSet<RightsType> RightsTypes { get; set; }
        public virtual DbSet<CarOwner> CarOwner { get; set; }
        public virtual DbSet<OwnerFine> OwnerFines { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Model> Models { get; set; }
    }
}
