//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public int RightTypeId { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual RightsType RightsTypes { get; set; }
        public virtual Owner Owners { get; set; }
    }
}
